### ISSUE TITLE
ES108FC1

### ISSUE THREAD

**Issue by vdp** [Hanley-Yao/Zynq7010_eink_controller#1]
Hi,
I'd like to ask you a few questions about the ES108FC1 screen, if you don't mind...

I am experimenting with my own eink controller, and it works with 6" screens bought on AliExpress. When I tried to drive ES108FC1, however, it only updates from time to time and just behaves weirdly.

I saw your videos that show you've succeeded to drive it. May I ask where did you buy the screen? If it's AliExpress, from which seller did you buy it?

In one of your videos, you solder some component to make the screen work. Was it the pull-up resistor on the XON pin or something else?

https://www.bilibili.com/video/BV1qU4y1r7uo/

Thanks in advance!

**Comment by Hanley-Yao** [comment]
我的屏幕是从 咸鱼 买的，如果你的屏幕在控制器正常运行的情况下毫无反应可能是由于转接板与屏幕实际pin对应错误。可以尝试找联想C930双屏笔记本电脑主板的原理图参考墨水屏连接部分。

**Comment by Hanley-Yao** [comment]
你好 我的英文不太好。我的屏幕上从咸鱼上购买的。如果你的屏幕毫无反应可能是因为转接板画错了，这款屏幕是ThinkBook Plus的副屏，可以找个主板参考一下pin的映射关系。

**Comment by vdp** [comment]
Thanks for your help!

I've tried to verify my adapter board and didn't find problems. The panel pinout I'm using is from this datasheet:

https://github.com/vroland/epdiy/files/10342125/ES108FC1_Ver0.1.pdf

I will try to check for problems one more time.

I didn't realize that ES108FC1 was used as a second screen(and keyboard!) for Lenovo Yoga C930(and ThinkBook Plus, I guess)- that's very good to know. I've tried to find the schematic for its motherboard but the only sites I found, that claim to have it, want to charge me $20 for the privilege, which is a bit much in my opinion... I will continue to search for it. I think it might be available on badcaps.net, but it's down for maintenance at the moment, apparently.

Sorry for being too insistent, perhaps, but I'm still curious about the board fix that you show at the beginning of this video:

https://www.bilibili.com/video/BV1qU4y1r7uo/

If you don't mind me asking, what is the component that was soldered and where it was installed?

Thanks!

**Comment by Xavier1989** [comment]
> Thanks for your help!
> 
> I've tried to verify my adapter board and didn't find problems. The panel pinout I'm using is from this datasheet:
> 
> https://github.com/vroland/epdiy/files/10342125/ES108FC1_Ver0.1.pdf
> 
> I will try to check for problems one more time.
> 
> I didn't realize that ES108FC1 was used as a second screen(and keyboard!) for Lenovo Yoga C930(and ThinkBook Plus, I guess)- that's very good to know. I've tried to find the schematic for its motherboard but the only sites I found, that claim to have it, want to charge me $20 for the privilege, which is a bit much in my opinion... I will continue to search for it. I think it might be available on badcaps.net, but it's down for maintenance at the moment, apparently.
> 
> Sorry for being too insistent, perhaps, but I'm still curious about the board fix that you show at the beginning of this video:
> 
> https://www.bilibili.com/video/BV1qU4y1r7uo/
> 
> If you don't mind me asking, what is the component that was soldered and where it was installed?
> 
> Thanks!

The 50 connetion pin description in ES108FC1_Ver0.1.pdf file is different with this project. 
eg. Pin 6 is SPV in pdf file but NC in this project.
Maybe you can use this pin description and try again.
<img width="602" alt="截屏2023-09-05 22 03 11" src="https://github.com/Hanley-Yao/Zynq7010_eink_controller/assets/11469127/30818eeb-c505-4021-a579-cd006a06cfe8">

**Comment by vdp** [comment]
Hi, and sorry for the late reply!

I got distracted by other things lately and didn't have a chance to play with that screen much. Thanks a lot for the schematic! I'll study it more carefully as soon as I can. BTW, Wenting Zhang's "NekoInk" project supports this screen and he was kind enough to point out some differences between the pinout from the draft datasheet and the one he actually found to work https://github.com/zephray/NekoInk/issues/1 

I'm a bit rusty on the details right now but will compare your schematic to the one used in NekoInk when I get a chance.
