### ISSUE TITLE
请问哪一个是eink_controller.v？

### ISSUE THREAD

**Issue by Zxis233** [Hanley-Yao/Zynq7010_eink_controller#3]
在工程目录里搜索了下，似乎并没有呢
只有一个eink_controller_tb.v

**Comment by Hanley-Yao** [comment]
使用这个文件仿真，但是你大概率遇到错误，因为这个项目中的fdma会有跨4k读写操作，这在仿真中不被允许但是实际上可以正常工作https://github.com/Hanley-Yao/Zynq7010_eink_controller/blob/master/controller/Eink_controller_V1.0/Eink_controller_V1.0.srcs/sim_1/new/eink_controller_ed108_tb.v

**Comment by Zxis233** [comment]
> 使用这个文件仿真，但是你大概率遇到错误，因为这个项目中的fdma会有跨4k读写操作，这在仿真中不被允许但是实际上可以正常工作https://github.com/Hanley-Yao/Zynq7010_eink_controller/blob/master/controller/Eink_controller_V1.0/Eink_controller_V1.0.srcs/sim_1/new/eink_controller_ed108_tb.v

好的，感谢
