### ISSUE TITLE
et047tc1 電壓問題

### ISSUE THREAD

**Issue by briansune** [Hanley-Yao/Zynq7010_eink_controller#4]
你好，先感激提出了這開源例子。
對於et047tc1，我發現有黑粉殘留現象。
對於這問題我想問一下，安你的估計是因VCOM電壓不夠還是什麼?
還有的是，et047tc1的電壓你測試是設計了什麼的位置?
如VPOS VNEG VG+ VG-等

**Comment by Hanley-Yao** [comment]
麻烦发一下照片以供分析

**Comment by briansune** [comment]
@Hanley-Yao 

以 10101010 清白，無論怎刷結果都是一樣的黑粉殘留。

![image](https://github.com/Hanley-Yao/Zynq7010_eink_controller/assets/29487339/24e3a930-9bf2-40f3-9a70-f08f4f32b941)

我的電路板在測試ES108FC2時沒有黑粉殘留的現象。

**Comment by Hanley-Yao** [comment]
拍摄照片或者视频发我邮箱2116893813@qq.com

**Comment by Hanley-Yao** [comment]
这大概率不是供电的问题，以我多年的经验这应该是你屏幕坏了。

**Comment by briansune** [comment]
@Hanley-Yao 

我能控制出圖和不同的色。
你意思在上面能控制的情況下，這顯示都是有問題坏了的?

**Comment by briansune** [comment]
@Hanley-Yao 

我想確認一下，你那邊測試時所使用的電壓設定。
我這邊跟你設計看看是否有分別，如果再不行這可能要跟供應談一下質量出問題了。

**Comment by Hanley-Yao** [comment]
我的设计是VSH=+15V VSL=-15V VGH=+22V VGL=-20V VCOM根据屏幕标签说明的设定
实际上尺寸较大的屏幕VGH需要至高+28V的供电电压，但实际上提供+22V的电压就能正常工作

**Comment by briansune** [comment]
@Hanley-Yao 

能指點一下，VCOM根据屏幕标签说明的设定。
我的線上只是印了
ICA-FU-13C -1
94V-0 ichia 1504

![image](https://github.com/Hanley-Yao/Zynq7010_eink_controller/assets/29487339/c6a754cb-72ed-4eee-9a98-dbdb2369b78a)

這是代表了VCOM電壓嗎?

**Comment by Hanley-Yao** [comment]
![image_editor_1711812463300_edit_162542158328842.jpg](https://github.com/Hanley-Yao/Zynq7010_eink_controller/assets/33188393/4525dffd-9ace-42c7-9a5b-33a350f33697)

不清楚你屏幕具体情况，一般是在这个位置，如果没有明文写出，就需要扫码获得

**Comment by briansune** [comment]
@Hanley-Yao 

先感謝指導。
我試了跟你的思路掃QR 碼，但碼是傳回下方的文字。沒有顯示電壓數據。
根據你之前測試的情況，因我見你GITHUB是有測試et047tc1 這個顯示。

問題: 當時你所使用的VCOM數值是如何?

设计是VSH=+15V VSL=-15V VGH=+22V VGL=-20V
回答: 我現在的電壓設定都是對上你的。

**Comment by Hanley-Yao** [comment]
经验上错误的vcom不会导致你这样的问题，每块屏幕的vcom基本不相同无需纠结我测试时使用的vcom

**Comment by briansune** [comment]
@Hanley-Yao 

明白，老實說我的思路也是這樣。因為VCOM是全局性提供，又怎可能會引起指定區的黑點出問題。
我這邊也溝通了，叫供應補發新的再做測試算了。

但這個問題完結前我想問一下，VCOM其實影響什麼。確實是怎樣調?

**Comment by Hanley-Yao** [comment]
vcom就是根据屏幕标签上给的设置没有任何特殊处理，vcom的影响网络上有很多资料可查，我说的不一定准确

**Comment by briansune** [comment]
@Hanley-Yao 

好的，那我關了這次提問。
