### ISSUE TITLE
灰階表如何找或測試

### ISSUE THREAD

**Issue by briansune** [Hanley-Yao/Zynq7010_eink_controller#5]
@Hanley-Yao 

有另一組問題想指導一下。
在你開發和測試過程，表示的灰及階色板你是如何測試或拿到?
依我理解的控制，一般只有01和10的寫黑寫白。所以我估計的方式是用多次寫黑或白而引出灰階的深淺度。
不知這思路是否正確?

**Comment by Hanley-Yao** [comment]
正确的

**Comment by Hanley-Yao** [comment]
正确是，本项目原理上可以支持灰度刷新，但是并未实现

**Comment by briansune** [comment]
@Hanley-Yao 

你的意思是這個GITHUB上的例子出來的圖像只有黑白沒法達成灰階?
我想了解一下你的測試結果圖有灰階的影像產生，這一些灰階是怎樣控制出來?

**Comment by Hanley-Yao** [comment]
通过蓝噪声抖动算法产生的半色调图像实际每个像素点只有黑色或者白色两种状态

**Comment by briansune** [comment]
@Hanley-Yao 

![image](https://github.com/Hanley-Yao/Zynq7010_eink_controller/assets/29487339/230a7f32-35fd-41df-8e38-56c0233fd4bc)

這個都是依你所說的黑白點分佈灰階方式，而不是直接灰階出色?

**Comment by Hanley-Yao** [comment]
正确的

**Comment by briansune** [comment]
@Hanley-Yao 

受指教了。感激~

那我想問一問，如果我沒學習錯誤。一般顯示都是有一粒閃存的NAND 或NOR FLASH在顯示的接線上。
那個閃存是否就是存放了灰階的數據?

**Comment by Hanley-Yao** [comment]
正确的

**Comment by briansune** [comment]
@Hanley-Yao 

謝指教了。
