### ISSUE TITLE
控制電壓最終平均值問題

### ISSUE THREAD

**Issue by briansune** [Hanley-Yao/Zynq7010_eink_controller#6]
@Hanley-Yao 

再次感謝之前的解答。
在網上學習和測試的過程，我見有用家說明代碼和電壓之間的關係。
他們說明，最終平均電壓必須是0V。意思是在時間上+15V，-15V，VCOM 的合計最終平均值要得出0。
但在灰階的控制下，01和10之前的次數是不同的，而VCOM 00 的次數也是不同。
基終上說的情況下平均電壓也是沒法得出0V。
為什麼要0V是因為他們說不這樣平均回0V會傷害顯示。

基終上述的背景，他覺得墨水屏是跟LCD屏一樣要平均值回0V嗎?

**Comment by Hanley-Yao** [comment]
需要考虑直流平横问题

**Comment by briansune** [comment]
@Hanley-Yao 

你的意思是控制波形由時點0開始到Tn的合計平均=VCOM 還是0V?
因為 VCOM 代碼00就是 一個DC的負值，平衡在黑白上只有3個電壓值。
這3個電壓值在對同的FRAME時間是沒法做到合計平均=0V。

**Comment by Hanley-Yao** [comment]
屏幕的具体工作原理我没有研究，我只知道按照官方要求供电，波形使用官方提供的波形，其他方面的问题没有过多考虑

**Comment by briansune** [comment]
@Hanley-Yao 

波形使用官方提供的波形，你所指的是在SPI FLASH的那一些還是?因為FLASH內的波形直接解讀是沒法理解的。

**Comment by Hanley-Yao** [comment]
https://github.com/zephray/NekoInk/tree/master/utils
提供了wbf波形文件的解析

**Comment by briansune** [comment]
@Hanley-Yao 

能指點一下，我是用閃存的讀寫器把BIN拿出來的或HEX。
那個WBF是什麼格式?
你使用那UTILS內的程序去提取的步驟等

感謝~

**Comment by Hanley-Yao** [comment]
我没试过给你推荐的那个工具，我是使用我另一个开源项目进行波形逆向工程，但是需要使用it8951作为wbf解析工具并刷新特定图像。管用直接dump的工具请询问对应作者

**Comment by Hanley-Yao** [comment]
我不清楚，请询问对应的开发人员

**Comment by briansune** [comment]
@Hanley-Yao 

你不清楚的意思是你沒有引用那一位開發人員所提供的腳本去讀出SPI FLASH的波型數值?
那你所引用的波引數值是在那裡提出的?

**Comment by Hanley-Yao** [comment]
这个方法已经过时了，非常麻烦我不推荐https://github.com/Hanley-Yao/WaveHack

**Comment by briansune** [comment]
@Hanley-Yao 

感謝2個的例子提供。我都測試了2個網內的方案，但無法把完整的波形提取。過程中會是記憶體區段錯誤。
我想問下你黑和白的波形數據是在那我想計算一下合計平均值。

**Comment by Hanley-Yao** [comment]
https://github.com/Hanley-Yao/WaveHack/tree/main/analysis%2FED097TC2%2FGC16%2F24-27
