### ISSUE TITLE
Where can I buy v2?

### ISSUE THREAD

**Issue by Mibanfi** [Hanley-Yao/Zynq7010_eink_controller#7]
Hello!
I'm not sure this is the right place to post, but I don't know how else to contact you.
I've heard you have made a second version of this project under proprietary license, and are selling it online.
Is it true? If so, where can I buy it?
Thank you in advance.

**Comment by Hanley-Yao** [comment]
计划在未来三个月内上市，仅在中国大陆电商平台提供…国外不太清楚销售流程以及当地相关规定，如果可以您可以协助我


Hanley-Yao
***@***.***








------------------ Original ------------------
From: Mibanfi ***@***.***&gt;
Date: Sun,Oct 13,2024 11:23 PM
To: Hanley-Yao/Zynq7010_eink_controller ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [Hanley-Yao/Zynq7010_eink_controller] Where can I buy v2? (Issue #7)

**Comment by Mibanfi** [comment]
I don't know either, but I think some sites ship to other countries.
Anyways, I'll stay tuned and follow your project with excitement!
Thank you so much for the very fast reply.

**Comment by Hanley-Yao** [comment]
谢谢关注，可以请问您从哪里了解到此项目的更多信息的？

**Comment by Mibanfi** [comment]
I heard of it from Zephray

**Comment by Hanley-Yao** [comment]
👌
